export const chainData = [
  {
    chain_id: 1,
    chain_name: "Ethereum",
    maintainer_id: "ethereum",
    endpoints: {
      rpc: [
        "https://rpc.ankr.com/eth",
        "https://cloudflare-eth.com",
        "https://ethereum.blockpi.network/v1/rpc/public",
        "https://1rpc.io/eth",
        "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
      ],
    },
    native_token: {
      name: "Ethereum",
      symbol: "ETH",
      decimals: 18,
    },
    name: "Ethereum",
    short_name: "ETH",
    image: "/logos/chains/ethereum.svg",
    color: "#c0c2c3",
    explorer: {
      name: "Etherscan",
      url: "https://etherscan.io",
      icon: "/logos/explorers/etherscan.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "ethereum",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x1",
        chainName: "Ethereum Mainnet",
        rpcUrls: [
          "https://rpc.ankr.com/eth",
          "https://cloudflare-eth.com",
          "https://ethereum.blockpi.network/v1/rpc/public",
          "https://1rpc.io/eth",
          "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
        ],
        nativeCurrency: {
          name: "Ethereum",
          symbol: "ETH",
          decimals: 18,
        },
        blockExplorerUrls: ["https://etherscan.io"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 56,
    chain_name: "binance",
    maintainer_id: "binance",
    endpoints: {
      rpc: [
        "https://bsc-dataseed1.defibit.io",
        "https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3",
        "https://1rpc.io/bnb",
        "https://bscrpc.com",
        "https://rpc.ankr.com/bsc",
      ],
    },
    native_token: {
      name: "BNB",
      symbol: "BNB",
      decimals: 18,
    },
    name: "BNB Chain",
    short_name: "BNB",
    image: "/logos/chains/binance.png",
    color: "#e8b30b",
    explorer: {
      name: "BscScan",
      url: "https://bscscan.com",
      icon: "/logos/explorers/bscscan.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "binance",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x38",
        chainName: "BNB Chain Mainnet",
        rpcUrls: [
          "https://bsc-dataseed1.defibit.io",
          "https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3",
          "https://1rpc.io/bnb",
          "https://bscrpc.com",
          "https://rpc.ankr.com/bsc",
        ],
        nativeCurrency: {
          name: "BNB",
          symbol: "BNB",
          decimals: 18,
        },
        blockExplorerUrls: ["https://bscscan.com"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 137,
    chain_name: "Polygon",
    maintainer_id: "polygon",
    endpoints: {
      rpc: [
        "https://polygon-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
        "https://polygon.blockpi.network/v1/rpc/public",
        "https://1rpc.io/matic",
        "https://rpc.ankr.com/polygon",
      ],
    },
    native_token: {
      name: "Polygon",
      symbol: "MATIC",
      decimals: 18,
    },
    name: "Polygon",
    short_name: "POLYGON",
    image: "/logos/chains/polygon.svg",
    color: "#8247e5",
    explorer: {
      name: "Polygonscan",
      url: "https://polygonscan.com",
      icon: "/logos/explorers/polygonscan.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "polygon",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x89",
        chainName: "Polygon Mainnet",
        rpcUrls: [
          "https://polygon-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
          "https://polygon.blockpi.network/v1/rpc/public",
          "https://1rpc.io/matic",
          "https://rpc.ankr.com/polygon",
        ],
        nativeCurrency: {
          name: "Polygon",
          symbol: "MATIC",
          decimals: 18,
        },
        blockExplorerUrls: ["https://polygonscan.com"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 43114,
    chain_name: "Avalanche",
    maintainer_id: "avalanche",
    endpoints: {
      rpc: [
        "https://avalanche.blockpi.network/v1/rpc/public",
        "https://1rpc.io/avax/c",
        "https://rpc.ankr.com/avalanche",
      ],
    },
    native_token: {
      name: "Avalanche",
      symbol: "AVAX",
      decimals: 18,
    },
    name: "Avalanche",
    short_name: "AVAX",
    image: "/logos/chains/avalanche.svg",
    color: "#e84143",
    explorer: {
      name: "Snowtrace",
      url: "https://snowtrace.io",
      icon: "/logos/explorers/snowtrace.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "avalanche",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0xa86a",
        chainName: "Avalanche Mainnet",
        rpcUrls: [
          "https://avalanche.blockpi.network/v1/rpc/public",
          "https://1rpc.io/avax/c",
          "https://rpc.ankr.com/avalanche",
        ],
        nativeCurrency: {
          name: "Avalanche",
          symbol: "AVAX",
          decimals: 18,
        },
        blockExplorerUrls: ["https://snowtrace.io"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 250,
    chain_name: "Fantom",
    maintainer_id: "fantom",
    endpoints: {
      rpc: [
        "https://rpc.ftm.tools",
        "https://rpc.fantom.network",
        "https://fantom.blockpi.network/v1/rpc/public",
        "https://1rpc.io/ftm",
        "https://rpc.ankr.com/fantom",
      ],
    },
    native_token: {
      name: "Fantom",
      symbol: "FTM",
      decimals: 18,
    },
    name: "Fantom",
    short_name: "FTM",
    image: "/logos/chains/fantom.svg",
    color: "#1869ff",
    explorer: {
      name: "FTMScan",
      url: "https://ftmscan.com",
      icon: "/logos/explorers/ftmscan.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "fantom",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0xfa",
        chainName: "Fantom Mainnet",
        rpcUrls: [
          "https://rpc.ftm.tools",
          "https://rpc.fantom.network",
          "https://fantom.blockpi.network/v1/rpc/public",
          "https://1rpc.io/ftm",
          "https://rpc.ankr.com/fantom",
        ],
        nativeCurrency: {
          name: "Fantom",
          symbol: "FTM",
          decimals: 18,
        },
        blockExplorerUrls: ["https://ftmscan.com"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 1284,
    chain_name: "Moonbeam",
    maintainer_id: "moonbeam",
    endpoints: {
      rpc: [
        "https://rpc.api.moonbeam.network",
        "https://1rpc.io/glmr",
        "https://rpc.ankr.com/moonbeam",
      ],
    },
    native_token: {
      name: "Moonbeam",
      symbol: "GLMR",
      decimals: 18,
    },
    name: "Moonbeam",
    short_name: "MOONBEAM",
    image: "/logos/chains/moonbeam.svg",
    color: "#53cbc8",
    explorer: {
      name: "Moonscan",
      url: "https://moonscan.io",
      icon: "/logos/explorers/moonbeam.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "moonbeam",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x504",
        chainName: "Moonbeam Mainnet",
        rpcUrls: [
          "https://rpc.api.moonbeam.network",
          "https://1rpc.io/glmr",
          "https://rpc.ankr.com/moonbeam",
        ],
        nativeCurrency: {
          name: "Moonbeam",
          symbol: "GLMR",
          decimals: 18,
        },
        blockExplorerUrls: ["https://moonscan.io"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 1313161554,
    chain_name: "aurora",
    maintainer_id: "aurora",
    deprecated: true,
    endpoints: {
      rpc: ["https://mainnet.aurora.dev"],
    },
    native_token: {
      name: "Ethereum",
      symbol: "aETH",
      decimals: 18,
    },
    name: "Aurora",
    short_name: "AURORA",
    image: "/logos/chains/aurora.svg",
    color: "#88d060",
    explorer: {
      name: "Aurora",
      url: "https://explorer.aurora.dev",
      icon: "/logos/explorers/aurorascan.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "aurora",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x4e454152",
        chainName: "Aurora Mainnet",
        rpcUrls: ["https://mainnet.aurora.dev"],
        nativeCurrency: {
          name: "Ethereum",
          symbol: "aETH",
          decimals: 18,
        },
        blockExplorerUrls: ["https://explorer.aurora.dev"],
      },
    ],
    no_inflation: true,
    no_tvl: true,
  },
  {
    chain_id: 42161,
    chain_name: "arbitrum",
    maintainer_id: "arbitrum",
    endpoints: {
      rpc: [
        "https://1rpc.io/arb",
        "https://arbitrum-one.public.blastapi.io",
        "https://arbitrum.blockpi.network/v1/rpc/public",
        "https://rpc.ankr.com/arbitrum",
        "https://arbitrum-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
      ],
    },
    native_token: {
      name: "Ethereum",
      symbol: "ETH",
      decimals: 18,
    },
    name: "Arbitrum",
    short_name: "ARB",
    image: "/logos/chains/arbitrum.svg",
    color: "#28a0f0",
    explorer: {
      name: "Arbiscan",
      url: "https://arbiscan.io",
      icon: "/logos/explorers/arbiscan.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "arbitrum",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0xa4b1",
        chainName: "Arbitrum Mainnet",
        rpcUrls: [
          "https://1rpc.io/arb",
          "https://arbitrum-one.public.blastapi.io",
          "https://arbitrum.blockpi.network/v1/rpc/public",
          "https://rpc.ankr.com/arbitrum",
          "https://arbitrum-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
        ],
        nativeCurrency: {
          name: "Ethereum",
          symbol: "ETH",
          decimals: 18,
        },
        blockExplorerUrls: ["https://arbiscan.io"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 10,
    chain_name: "optimism",
    maintainer_id: "optimism",
    endpoints: {
      rpc: [
        "https://optimism-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
        "https://optimism.blockpi.network/v1/rpc/public",
        "https://1rpc.io/op",
        "https://rpc.ankr.com/optimism",
      ],
    },
    native_token: {
      name: "Ethereum",
      symbol: "ETH",
      decimals: 18,
    },
    name: "Optimism",
    short_name: "OP",
    image: "/logos/chains/optimism.svg",
    color: "#dc2626",
    explorer: {
      name: "Etherscan",
      url: "https://optimistic.etherscan.io",
      icon: "/logos/explorers/optimism.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "optimism",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0xa",
        chainName: "Optimism Mainnet",
        rpcUrls: [
          "https://optimism-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
          "https://optimism.blockpi.network/v1/rpc/public",
          "https://1rpc.io/op",
          "https://rpc.ankr.com/optimism",
        ],
        nativeCurrency: {
          name: "Ethereum",
          symbol: "ETH",
          decimals: 18,
        },
        blockExplorerUrls: ["https://optimistic.etherscan.io"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 8453,
    chain_name: "base",
    maintainer_id: "base",
    endpoints: {
      rpc: ["https://developer-access-mainnet.base.org"],
    },
    native_token: {
      name: "Ethereum",
      symbol: "ETH",
      decimals: 18,
    },
    name: "Base",
    short_name: "BASE",
    image: "/logos/chains/base.svg",
    color: "#0052fe",
    explorer: {
      name: "Basescan",
      url: "https://basescan.org",
      icon: "/logos/explorers/basescan.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "base",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x2105",
        chainName: "Base Mainnet",
        rpcUrls: ["https://developer-access-mainnet.base.org"],
        nativeCurrency: {
          name: "Ethereum",
          symbol: "ETH",
          decimals: 18,
        },
        blockExplorerUrls: ["https://basescan.org"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 5000,
    chain_name: "mantle",
    maintainer_id: "mantle",
    endpoints: {
      rpc: [
        "https://rpc.mantle.xyz",
        "https://mantle-mainnet.public.blastapi.io",
      ],
    },
    native_token: {
      name: "Mantle",
      symbol: "MNT",
      decimals: 18,
    },
    name: "Mantle",
    short_name: "MNT",
    image: "/logos/chains/mantle.svg",
    color: "#65b3ae",
    explorer: {
      name: "Mantle",
      url: "https://explorer.mantle.xyz",
      icon: "/logos/explorers/mantle.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "mantle",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x1388",
        chainName: "Mantle Mainnet",
        rpcUrls: [
          "https://rpc.mantle.xyz",
          "https://mantle-mainnet.public.blastapi.io",
        ],
        nativeCurrency: {
          name: "Mantle",
          symbol: "MNT",
          decimals: 18,
        },
        blockExplorerUrls: ["https://explorer.mantle.xyz"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 42220,
    chain_name: "celo",
    maintainer_id: "celo",
    endpoints: {
      rpc: [
        "https://forno.celo.org",
        "https://1rpc.io/celo",
        "https://rpc.ankr.com/celo",
      ],
    },
    native_token: {
      name: "Celo",
      symbol: "CELO",
      decimals: 18,
    },
    name: "Celo",
    short_name: "CELO",
    image: "/logos/chains/celo.svg",
    color: "#35d07f",
    explorer: {
      name: "Celoscan",
      url: "https://celoscan.io",
      icon: "/logos/explorers/celoscan.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "celo",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0xa4ec",
        chainName: "Celo Mainnet",
        rpcUrls: [
          "https://forno.celo.org",
          "https://1rpc.io/celo",
          "https://rpc.ankr.com/celo",
        ],
        nativeCurrency: {
          name: "Celo",
          symbol: "CELO",
          decimals: 18,
        },
        blockExplorerUrls: ["https://celoscan.io"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 2222,
    chain_name: "kava",
    maintainer_id: "kava",
    endpoints: {
      rpc: [
        "https://evm.data.axelar.kava.io",
        "https://kava-evm.publicnode.com",
      ],
    },
    native_token: {
      name: "Kava",
      symbol: "KAVA",
      decimals: 18,
    },
    name: "Kava",
    short_name: "KAVA",
    image: "/logos/chains/kava.svg",
    color: "#ff433e",
    explorer: {
      name: "Kava",
      url: "https://explorer.kava.io",
      icon: "/logos/explorers/kava.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "kava",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x8ae",
        chainName: "Kava Mainnet",
        rpcUrls: [
          "https://evm.data.axelar.kava.io",
          "https://kava-evm.publicnode.com",
        ],
        nativeCurrency: {
          name: "Kava",
          symbol: "KAVA",
          decimals: 18,
        },
        blockExplorerUrls: ["https://explorer.kava.io"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 314,
    chain_name: "filecoin",
    maintainer_id: "filecoin",
    no_recover: true,
    endpoints: {
      rpc: [
        "https://filfox.info/rpc/v1",
        "https://api.chain.love/rpc/v1",
        "https://filecoin.chainup.net/rpc/v1",
        "https://rpc.ankr.com/filecoin",
        "https://api.node.glif.io",
      ],
    },
    native_token: {
      name: "Filecoin",
      symbol: "FIL",
      decimals: 18,
    },
    name: "Filecoin",
    short_name: "FIL",
    image: "/logos/chains/filecoin.svg",
    color: "#0090ff",
    explorer: {
      name: "Filecoin",
      url: "https://filfox.info",
      icon: "/logos/explorers/filecoin.png",
      block_path: "/tipset/{block}",
      address_path: "/address/{address}",
      contract_path: "/address/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "filecoin",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x13a",
        chainName: "Filecoin Mainnet",
        rpcUrls: [
          "https://filfox.info/rpc/v1",
          "https://api.chain.love/rpc/v1",
          "https://filecoin.chainup.net/rpc/v1",
          "https://rpc.ankr.com/filecoin",
          "https://api.node.glif.io",
        ],
        nativeCurrency: {
          name: "Filecoin",
          symbol: "FIL",
          decimals: 18,
        },
        blockExplorerUrls: ["https://filfox.info"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 59144,
    chain_name: "linea",
    maintainer_id: "linea",
    endpoints: {
      rpc: [
        "https://linea-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
      ],
    },
    native_token: {
      name: "Ethereum",
      symbol: "ETH",
      decimals: 18,
    },
    name: "Linea",
    short_name: "LINEA",
    image: "/logos/chains/linea.svg",
    color: "#62dfff",
    explorer: {
      name: "Linea",
      url: "https://lineascan.build",
      icon: "/logos/explorers/linea.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "linea",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0xe708",
        chainName: "Linea Mainnet",
        rpcUrls: [
          "https://linea-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
        ],
        nativeCurrency: {
          name: "Ethereum",
          symbol: "ETH",
          decimals: 18,
        },
        blockExplorerUrls: ["https://lineascan.build"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 2031,
    chain_name: "centrifuge",
    maintainer_id: "centrifuge",
    no_recover: true,
    no_tvl: true,
    endpoints: {
      rpc: ["https://fullnode.parachain.centrifuge.io"],
    },
    native_token: {
      name: "Centrifuge",
      symbol: "CFG",
      decimals: 18,
    },
    name: "Centrifuge",
    short_name: "CFG",
    image: "/logos/chains/centrifuge.svg",
    color: "#ffc012",
    explorer: {
      name: "Centrifuge",
      url: "https://centrifuge.subscan.io",
      icon: "/logos/explorers/centrifuge.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/extrinsic/{tx}",
    },
    id: "centrifuge",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x7ef",
        chainName: "Centrifuge Mainnet",
        rpcUrls: ["https://fullnode.parachain.centrifuge.io"],
        nativeCurrency: {
          name: "Centrifuge",
          symbol: "CFG",
          decimals: 18,
        },
        blockExplorerUrls: ["https://centrifuge.subscan.io"],
      },
    ],
    no_inflation: false,
  },
  {
    chain_id: 534352,
    chain_name: "scroll",
    maintainer_id: "scroll",
    endpoints: {
      rpc: ["https://rpc.scroll.io"],
    },
    native_token: {
      name: "Ethereum",
      symbol: "ETH",
      decimals: 18,
    },
    name: "Scroll",
    short_name: "SCROLL",
    image: "/logos/chains/scroll.svg",
    color: "#e4b67c",
    explorer: {
      name: "Scrollscan",
      url: "https://scrollscan.com",
      icon: "/logos/explorers/scroll.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "scroll",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x82750",
        chainName: "Scroll Mainnet",
        rpcUrls: ["https://rpc.scroll.io"],
        nativeCurrency: {
          name: "Ethereum",
          symbol: "ETH",
          decimals: 18,
        },
        blockExplorerUrls: ["https://scrollscan.com"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 13371,
    chain_name: "immutable",
    maintainer_id: "immutable",
    endpoints: {
      rpc: ["https://rpc.immutable.com"],
    },
    native_token: {
      name: "ImmutableX",
      symbol: "IMX",
      decimals: 18,
    },
    name: "Immutable",
    short_name: "IMX",
    image: "/logos/chains/immutable.svg",
    color: "#0d0d0d",
    explorer: {
      name: "Immutable",
      url: "https://explorer.immutable.com",
      icon: "/logos/explorers/immutable.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "immutable",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x343b",
        chainName: "Immutable Mainnet",
        rpcUrls: ["https://rpc.immutable.com"],
        nativeCurrency: {
          name: "ImmutableX",
          symbol: "IMX",
          decimals: 18,
        },
        blockExplorerUrls: ["https://explorer.immutable.com"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 252,
    chain_name: "fraxtal",
    maintainer_id: "fraxtal",
    endpoints: {
      rpc: ["https://rpc.frax.com"],
    },
    native_token: {
      name: "Frax Ether",
      symbol: "frxETH",
      decimals: 18,
    },
    name: "Fraxtal",
    short_name: "FRAXTAL",
    image: "/logos/chains/fraxtal.svg",
    color: "#111111",
    explorer: {
      name: "Fraxtal",
      url: "https://fraxscan.com",
      icon: "/logos/explorers/fraxtal.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "fraxtal",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0xfc",
        chainName: "Fraxtal Mainnet",
        rpcUrls: ["https://rpc.frax.com"],
        nativeCurrency: {
          name: "Frax Ether",
          symbol: "frxETH",
          decimals: 18,
        },
        blockExplorerUrls: ["https://fraxscan.com"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: 81457,
    chain_name: "blast",
    maintainer_id: "blast",
    endpoints: {
      rpc: [
        "https://rpc.ankr.com/blast",
        "https://blast.blockpi.network/v1/rpc/public",
      ],
    },
    native_token: {
      name: "Ethereum",
      symbol: "ETH",
      decimals: 18,
    },
    name: "Blast",
    short_name: "BLAST",
    image: "/logos/chains/blast.svg",
    color: "#fefb1c",
    explorer: {
      name: "Blast",
      url: "https://blastscan.io",
      icon: "/logos/explorers/blast.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/token/{address}",
      transaction_path: "/tx/{tx}",
    },
    id: "blast",
    chain_type: "evm",
    provider_params: [
      {
        chainId: "0x13e31",
        chainName: "Blast Mainnet",
        rpcUrls: [
          "https://rpc.ankr.com/blast",
          "https://blast.blockpi.network/v1/rpc/public",
        ],
        nativeCurrency: {
          name: "Ethereum",
          symbol: "ETH",
          decimals: 18,
        },
        blockExplorerUrls: ["https://blastscan.io"],
      },
    ],
    no_inflation: false,
    no_tvl: false,
  },
  {
    chain_id: "axelar-dojo-1",
    chain_name: "Axelarnet",
    aliases: ["axelar"],
    endpoints: {
      lcd: [
        "https://lcd-axelar.imperator.co",
        "https://axelar-rest.chainode.tech",
        "https://axelar-lcd.qubelabs.io",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Axelar",
      symbol: "AXL",
      denom: "uaxl",
      decimals: 6,
    },
    name: "Axelar",
    short_name: "AXELAR",
    image: "/logos/chains/axelarnet.svg",
    color: "#abaaaa",
    explorer: {
      name: "Axelarscan",
      url: "https://axelarscan.io",
      icon: "/logos/explorers/axelarscan.svg",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/tx/{tx}",
    },
    prefix_address: "axelar",
    prefix_chain_ids: ["axelar-"],
    id: "axelarnet",
    chain_type: "cosmos",
  },
  {
    chain_id: "osmosis-1",
    chain_name: "osmosis",
    endpoints: {
      lcd: [
        "https://rest-osmosis.ecostake.com",
        "https://osmosis-api.polkachu.com",
        "https://lcd-osmosis.imperator.co",
        "https://lcd.osmosis.zone",
        "https://api-osmosis-ia.cosmosia.notional.ventures",
        "https://lcd-osmosis.blockapsis.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Osmosis",
      symbol: "OSMO",
      denom: "uosmo",
      decimals: 6,
    },
    name: "Osmosis",
    short_name: "OSMO",
    image: "/logos/chains/osmosis.svg",
    color: "#d705cc",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/osmosis",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "osmo",
    prefix_chain_ids: ["osmosis-"],
    id: "osmosis",
    chain_type: "cosmos",
  },
  {
    chain_id: "cosmoshub-4",
    chain_name: "cosmoshub",
    endpoints: {
      lcd: [
        "https://lcd-cosmos.imperator.co",
        "https://lcd-cosmoshub.whispernode.com/",
        "https://api-cosmoshub-ia.cosmosia.notional.ventures",
        "https://cosmos-api.polkachu.com",
        "https://lcd.cosmos.dragonstake.io",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Cosmos",
      symbol: "ATOM",
      denom: "uatom",
      decimals: 6,
    },
    name: "Cosmos",
    short_name: "COSMOS",
    image: "/logos/chains/cosmoshub.svg",
    color: "#2e3148",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/cosmos",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "cosmos",
    prefix_chain_ids: ["cosmoshub-"],
    id: "cosmoshub",
    chain_type: "cosmos",
  },
  {
    chain_id: "juno-1",
    chain_name: "juno",
    endpoints: {
      lcd: [
        "https://lcd-juno.imperator.co",
        "https://juno-api.polkachu.com",
        "https://lcd-juno.whispernode.com",
        "https://lcd-juno.itastakers.com",
        "https://api-juno-ia.cosmosia.notional.ventures",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Juno",
      symbol: "JUNO",
      denom: "ujuno",
      decimals: 6,
    },
    name: "Juno",
    short_name: "JUNO",
    image: "/logos/chains/juno.svg",
    color: "#f0827d",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/juno",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "juno",
    prefix_chain_ids: ["juno-"],
    id: "juno",
    chain_type: "cosmos",
  },
  {
    chain_id: "emoney-3",
    chain_name: "e-money",
    endpoints: {
      lcd: [
        "https://api-emoney-ia.cosmosia.notional.ventures",
        "https://emoney.validator.network/api",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "e-Money",
      symbol: "NGM",
      denom: "ungm",
      decimals: 6,
    },
    name: "e-Money",
    short_name: "E-MONEY",
    image: "/logos/chains/emoney.svg",
    color: "#002e33",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/emoney",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "emoney",
    prefix_chain_ids: ["emoney-"],
    id: "emoney",
    chain_type: "cosmos",
  },
  {
    chain_id: "injective-1",
    chain_name: "injective",
    endpoints: {
      lcd: [
        "https://api-injective-ia.cosmosia.notional.ventures",
        "https://sentry.lcd.injective.network",
        "https://injective-api.polkachu.com",
        "https://public.lcd.injective.network",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Injective",
      symbol: "INJ",
      denom: "uinj",
      decimals: 6,
    },
    name: "Injective",
    short_name: "INJ",
    image: "/logos/chains/injective.svg",
    color: "#00a3ba",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/injective",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "inj",
    prefix_chain_ids: ["injective-"],
    id: "injective",
    chain_type: "cosmos",
  },
  {
    chain_id: "crescent-1",
    chain_name: "crescent",
    endpoints: {
      lcd: [
        "https://crescent-api.polkachu.com",
        "https://mainnet.crescent.network:1317",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Crescent",
      symbol: "CRE",
      denom: "ucre",
      decimals: 6,
    },
    name: "Crescent",
    short_name: "CRE",
    image: "/logos/chains/crescent.svg",
    color: "#bf7c5e",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/crescent",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "cre",
    prefix_chain_ids: ["crescent-"],
    id: "crescent",
    chain_type: "cosmos",
  },
  {
    chain_id: "kaiyo-1",
    chain_name: "kujira",
    endpoints: {
      lcd: [
        "https://api-kujira-ia.cosmosia.notional.ventures",
        "https://kujira-api.polkachu.com",
        "https://lcd-kujira.imperator.co",
        "https://lcd-kujira.whispernode.com",
        "https://kujira-api.lavenderfive.com",
        "https://rest-kujira.ecostake.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Kujira",
      symbol: "KUJI",
      denom: "ukuji",
      decimals: 6,
    },
    name: "Kujira",
    short_name: "KUJI",
    image: "/logos/chains/kujira.svg",
    color: "#8b1227",
    explorer: {
      name: "Kujira",
      url: "https://finder.kujira.network/kaiyo-1",
      icon: "/logos/explorers/kujira.png",
      block_path: "/block/{block}",
      address_path: "/address/{address}",
      contract_path: "/contract/{address}",
      transaction_path: "/tx/{tx}",
    },
    prefix_address: "kujira",
    prefix_chain_ids: ["kaiyo-"],
    id: "kujira",
    chain_type: "cosmos",
  },
  {
    chain_id: "secret-4",
    chain_name: "secret-snip",
    endpoints: {
      lcd: [
        "https://secret-rest-sl.norm.io",
        "https://secretnetwork-lcd.stakely.io",
        "https://secret-4.api.trivium.network:1317",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Secret",
      symbol: "SCRT",
      denom: "uscrt",
      decimals: 6,
    },
    name: "Secret-SNIP",
    short_name: "SCRT-SNIP",
    image: "/logos/chains/secret.svg",
    color: "#000000",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/secret",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "secret",
    prefix_chain_ids: ["secret-"],
    id: "secret-snip",
    chain_type: "cosmos",
  },
  {
    chain_id: "secret-4",
    chain_name: "secret",
    endpoints: {
      lcd: [
        "https://secret-rest-sl.norm.io",
        "https://secretnetwork-lcd.stakely.io",
        "https://secret-4.api.trivium.network:1317",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Secret",
      symbol: "SCRT",
      denom: "uscrt",
      decimals: 6,
    },
    name: "Secret",
    short_name: "SCRT",
    image: "/logos/chains/secret.svg",
    color: "#000000",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/secret",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "secret",
    prefix_chain_ids: ["secret-"],
    id: "secret",
    chain_type: "cosmos",
  },
  {
    chain_id: "pacific-1",
    chain_name: "sei",
    endpoints: {
      lcd: [
        "https://sei-api.polkachu.com",
        "https://sei-rest.brocha.in",
        "https://rest.sei-apis.com",
        "https://sei-api.lavenderfive.com",
        "https://api-sei.stingray.plus",
        "https://lcd-sei.whispernode.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Sei",
      symbol: "SEI",
      denom: "usei",
      decimals: 6,
    },
    name: "Sei",
    short_name: "SEI",
    image: "/logos/chains/sei.svg",
    color: "#b5354f",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/sei",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "sei",
    prefix_chain_ids: ["pacific-"],
    id: "sei",
    chain_type: "cosmos",
  },
  {
    chain_id: "stargaze-1",
    chain_name: "stargaze",
    endpoints: {
      lcd: [
        "https://lcd-stargaze.imperator.co/",
        "https://api-stargaze-ia.cosmosia.notional.ventures",
        "https://stargaze-api.polkachu.com",
        "https://api-stargaze.ezstaking.dev",
        "https://stargaze-api.ibs.team",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Stargaze",
      symbol: "STARS",
      denom: "ustars",
      decimals: 6,
    },
    name: "Stargaze",
    short_name: "STARS",
    image: "/logos/chains/stargaze.svg",
    color: "#c2df78",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/stargaze",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "stars",
    prefix_chain_ids: ["stargaze-"],
    id: "stargaze",
    chain_type: "cosmos",
  },
  {
    chain_id: "mantle-1",
    chain_name: "assetmantle",
    endpoints: {
      lcd: [
        "https://api-assetmantle-ia.cosmosia.notional.ventures",
        "https://assetmantle-api.polkachu.com",
        "https://rest.assetmantle.one",
        "https://rest-assetmantle.ecostake.com",
        "https://api.assetmantle.nodestake.top",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "AssetMantle",
      symbol: "MNTL",
      denom: "umntl",
      decimals: 6,
    },
    name: "AssetMantle",
    short_name: "MNTL",
    image: "/logos/chains/assetmantle.svg",
    color: "#f5c15b",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/asset-mantle",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "mantle",
    prefix_chain_ids: ["mantle-"],
    id: "assetmantle",
    chain_type: "cosmos",
  },
  {
    chain_id: "fetchhub-4",
    chain_name: "fetch",
    endpoints: {
      lcd: [
        "https://rest-fetchhub.fetch.ai",
        "https://api-fetchhub-ia.cosmosia.notional.ventures",
        "https://fetch-api.polkachu.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Fetch.ai",
      symbol: "FET",
      denom: "ufet",
      decimals: 6,
    },
    name: "Fetch.ai",
    short_name: "FET",
    image: "/logos/chains/fetch.png",
    color: "#1e2744",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/fetchai",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "fetch",
    prefix_chain_ids: ["fetchhub-"],
    id: "fetch",
    chain_type: "cosmos",
  },
  {
    chain_id: "kichain-2",
    chain_name: "ki",
    endpoints: {
      lcd: [
        "https://api-mainnet.blockchain.ki",
        "https://lcd-kichain.imperator.co",
        "https://api-kichain-ia.cosmosia.notional.ventures/",
        "https://api.kichain.chaintools.tech",
        "https://kichain-api.polkachu.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "KI",
      symbol: "KI",
      denom: "uki",
      decimals: 6,
    },
    name: "KI",
    short_name: "KI",
    image: "/logos/chains/kichain.svg",
    color: "#2a4bfb",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/ki-chain",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "ki",
    prefix_chain_ids: ["kichain-"],
    id: "ki",
    chain_type: "cosmos",
  },
  {
    chain_id: "evmos_9001-2",
    chain_name: "evmos",
    endpoints: {
      lcd: [
        "https://api-evmos-ia.cosmosia.notional.ventures",
        "https://evmos-api.polkachu.com",
        "https://lcd-evmos.imperator.co",
        "https://evmos-api.lavenderfive.com",
        "https://rest-evmos.ecostake.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Evmos",
      symbol: "EVMOS",
      denom: "uevmos",
      decimals: 6,
    },
    name: "Evmos",
    short_name: "EVMOS",
    image: "/logos/chains/evmos.png",
    color: "#ed4e32",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/evmos",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "evmos",
    prefix_chain_ids: ["evmos_"],
    id: "evmos",
    chain_type: "cosmos",
  },
  {
    chain_id: "xstaxy-1",
    chain_name: "aura",
    endpoints: {
      lcd: ["https://lcd.aura.network"],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Aura",
      symbol: "AURA",
      denom: "uaura",
      decimals: 6,
    },
    name: "Aura",
    short_name: "AURA",
    image: "/logos/chains/aura.svg",
    color: "#7bdddc",
    explorer: {
      name: "Aurascan",
      url: "https://aurascan.io",
      icon: "/logos/explorers/aura.png",
      block_path: "/blocks/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/transaction/{tx}",
    },
    prefix_address: "aura",
    prefix_chain_ids: ["xstaxy-"],
    id: "aura",
    chain_type: "cosmos",
  },
  {
    chain_id: "comdex-1",
    chain_name: "comdex",
    endpoints: {
      lcd: [
        "https://comdex-api.polkachu.com",
        "https://lcd-comdex.imperator.co",
        "https://api.comdex.chaintools.tech",
        "https://rest.comdex.one",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Comdex",
      symbol: "CMDX",
      denom: "ucmdx",
      decimals: 6,
    },
    name: "Comdex",
    short_name: "CMDX",
    image: "/logos/chains/comdex.png",
    color: "#fe424f",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/comdex",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "comdex",
    prefix_chain_ids: ["comdex-"],
    id: "comdex",
    chain_type: "cosmos",
  },
  {
    chain_id: "core-1",
    chain_name: "persistence",
    endpoints: {
      lcd: [
        "https://rest.core.persistence.one",
        "https://persistence-api.polkachu.com",
        "https://persistence-api.kleomedes.network",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Persistence",
      symbol: "XPRT",
      denom: "uxprt",
      decimals: 6,
    },
    name: "Persistence",
    short_name: "XPRT",
    image: "/logos/chains/persistence.svg",
    color: "#e50813",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/persistence",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "persistence",
    prefix_chain_ids: ["core-"],
    id: "persistence",
    chain_type: "cosmos",
  },
  {
    chain_id: "regen-1",
    chain_name: "regen",
    endpoints: {
      lcd: [
        "https://api-regen-ia.cosmosia.notional.ventures",
        "https://regen.stakesystems.io",
        "https://rest-regen.ecostake.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Regen",
      symbol: "REGEN",
      denom: "uregen",
      decimals: 6,
    },
    name: "Regen",
    short_name: "REGEN",
    image: "/logos/chains/regen.svg",
    color: "#4fb573",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/regen",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "regen",
    prefix_chain_ids: ["regen-"],
    id: "regen",
    chain_type: "cosmos",
  },
  {
    chain_id: "umee-1",
    chain_name: "umee",
    endpoints: {
      lcd: [
        "https://api-umee-ia.cosmosia.notional.ventures",
        "https://umee-api.polkachu.com",
        "https://umee-lcd.quantnode.tech",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Umee",
      symbol: "UMEE",
      denom: "uumee",
      decimals: 6,
    },
    name: "Umee",
    short_name: "UMEE",
    image: "/logos/chains/umee.svg",
    color: "#fda9ff",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/umee",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "umee",
    prefix_chain_ids: ["umee-"],
    id: "umee",
    chain_type: "cosmos",
  },
  {
    chain_id: "agoric-3",
    chain_name: "agoric",
    endpoints: {
      lcd: [
        "https://agoric-api.polkachu.com",
        "https://main.api.agoric.net",
        "https://agoric.api.kjnodes.com",
        "https://api.agoric.nodestake.top",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Agoric",
      symbol: "BLD",
      denom: "ubld",
      decimals: 6,
    },
    name: "Agoric",
    short_name: "BLD",
    image: "/logos/chains/agoric.svg",
    color: "#bb2d40",
    explorer: {
      name: "Agoric",
      url: "https://agoric.explorers.guru",
      icon: "/logos/explorers/agoric.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/transaction/{tx}",
    },
    prefix_address: "agoric",
    prefix_chain_ids: ["agoric-"],
    id: "agoric",
    chain_type: "cosmos",
  },
  {
    chain_id: "dimension_37-1",
    chain_name: "xpla",
    endpoints: {
      lcd: [
        "https://xpla-api.polkachu.com",
        "https://dimension-lcd.xpla.io",
        "https://dimension-lcd.xpla.dev",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "XPLA",
      symbol: "XPLA",
      denom: "uxpla",
      decimals: 6,
    },
    name: "XPLA",
    short_name: "XPLA",
    image: "/logos/chains/xpla.svg",
    color: "#04a7f1",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/xpla",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "xpla",
    prefix_chain_ids: ["dimension_"],
    id: "xpla",
    chain_type: "cosmos",
  },
  {
    chain_id: "acre_9052-1",
    chain_name: "acre",
    aliases: ["acrechain"],
    endpoints: {
      lcd: [
        "https://lcd-acre.synergynodes.com",
        "https://rest.acre.tcnetwork.io",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Acrechain",
      symbol: "ACRE",
      denom: "uacre",
      decimals: 6,
    },
    name: "Acrechain",
    short_name: "ACRE",
    image: "/logos/chains/acre.svg",
    color: "#86c032",
    explorer: {
      name: "Acrechain",
      url: "https://cosmosrun.info/acre-mainnet",
      icon: "/logos/explorers/acre.png",
      block_path: "/blocks/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/tx/{tx}",
    },
    prefix_address: "acre",
    prefix_chain_ids: ["acre_"],
    id: "acre",
    chain_type: "cosmos",
  },
  {
    chain_id: "stride-1",
    chain_name: "stride",
    endpoints: {
      lcd: [
        "https://stride-api.polkachu.com",
        "https://stride-api.lavenderfive.com",
        "https://stride.api.kjnodes.com",
        "https://lcd-stride.whispernode.com",
        "https://api-stride.pupmos.network",
        "https://stride-api.stakeandrelax.net",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Stride",
      symbol: "STRD",
      denom: "ustrd",
      decimals: 6,
    },
    name: "Stride",
    short_name: "STRD",
    image: "/logos/chains/stride.svg",
    color: "#e90f79",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/stride",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "stride",
    prefix_chain_ids: ["stride-"],
    id: "stride",
    chain_type: "cosmos",
  },
  {
    chain_id: "carbon-1",
    chain_name: "carbon",
    endpoints: {
      lcd: [
        "https://rest.carbon.blockhunters.org",
        "https://rest.carbon.bh.rocks",
        "https://api.carbon.network",
      ],
      timeout: {
        lcd: 3000,
      },
      use_query: true,
    },
    native_token: {
      name: "Carbon",
      symbol: "SWTH",
      denom: "ustwh",
      decimals: 6,
    },
    name: "Carbon",
    short_name: "CARBON",
    image: "/logos/chains/carbon.svg",
    color: "#74e7e7",
    explorer: {
      name: "Carbon",
      url: "https://scan.carbon.network",
      icon: "/logos/explorers/carbon.png",
      block_path: "/block/{block}?net=main",
      address_path: "/account/{address}?net=main",
      contract_path: "/account/{address}?net=main",
      transaction_path: "/transaction/{tx}?net=main",
    },
    prefix_address: "swth",
    prefix_chain_ids: ["carbon-"],
    id: "carbon",
    chain_type: "cosmos",
  },
  {
    chain_id: "sommelier-3",
    chain_name: "sommelier",
    endpoints: {
      lcd: [
        "https://lcd-sommelier.imperator.co",
        "https://sommelier-api.polkachu.com",
        "https://rest.cosmos.directory/sommelier",
        "https://api-sommelier.pupmos.network",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Sommelier",
      symbol: "SOMM",
      denom: "usomm",
      decimals: 6,
    },
    name: "Sommelier",
    short_name: "SOMM",
    image: "/logos/chains/sommelier.svg",
    color: "#eb5d54",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/sommelier",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "somm",
    prefix_chain_ids: ["sommelier-"],
    id: "sommelier",
    chain_type: "cosmos",
  },
  {
    chain_id: "neutron-1",
    chain_name: "neutron",
    endpoints: {
      lcd: [
        "https://rest-kralum.neutron-1.neutron.org",
        "https://neutron-api.lavenderfive.com",
        "https://api.novel.remedy.tm.p2p.org",
      ],
      timeout: {
        lcd: 3000,
      },
      use_query: true,
    },
    native_token: {
      name: "Neutron",
      symbol: "NTRN",
      denom: "untrn",
      decimals: 6,
    },
    name: "Neutron",
    short_name: "NTRN",
    image: "/logos/chains/neutron.svg",
    color: "#131928",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/neutron",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "neutron",
    prefix_chain_ids: ["neutron-"],
    id: "neutron",
    chain_type: "cosmos",
  },
  {
    chain_id: "reb_1111-1",
    chain_name: "rebus",
    endpoints: {
      lcd: [
        "https://rebus.api.m.stavr.tech",
        "https://api-1.rebus.nodes.guru",
        "https://api.mainnet.rebus.money:1317",
        "https://rebus-mainnet-lcd.autostake.com",
        "https://rebus-rest.brocha.in",
        "https://rebus-rest.publicnode.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Rebus",
      symbol: "REBUS",
      denom: "urebus",
      decimals: 6,
    },
    name: "Rebus",
    short_name: "REBUS",
    image: "/logos/chains/rebus.svg",
    color: "#e95075",
    explorer: {
      name: "Rebus",
      url: "https://rebus.explorers.guru",
      icon: "/logos/explorers/rebus.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/transaction/{tx}",
    },
    prefix_address: "rebus",
    prefix_chain_ids: ["reb_"],
    id: "rebus",
    chain_type: "cosmos",
  },
  {
    chain_id: "archway-1",
    chain_name: "archway",
    endpoints: {
      lcd: [
        "https://api.mainnet.archway.io",
        "https://m-archway.api.utsa.tech",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Archway",
      symbol: "ARCH",
      denom: "uarch",
      decimals: 6,
    },
    name: "Archway",
    short_name: "ARCH",
    image: "/logos/chains/archway.svg",
    color: "#fe4d00",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/archway",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "archway",
    prefix_chain_ids: ["archway-"],
    id: "archway",
    chain_type: "cosmos",
  },
  {
    chain_id: "pio-mainnet-1",
    chain_name: "provenance",
    endpoints: {
      lcd: [
        "https://api.provenance.io",
        "https://api-provenance.takeshi.team",
        "https://provenance-api.ibs.team",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Provenance",
      symbol: "HASH",
      denom: "uhash",
      decimals: 6,
    },
    name: "Provenance",
    short_name: "HASH",
    image: "/logos/chains/provenance.svg",
    color: "#4d7fdb",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/provenance",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "pb",
    prefix_chain_ids: ["pio-"],
    id: "provenance",
    chain_type: "cosmos",
  },
  {
    chain_id: "ixo-5",
    chain_name: "ixo",
    endpoints: {
      lcd: [
        "https://api-ixo-ia.cosmosia.notional.ventures",
        "https://impacthub-api.lavenderfive.com",
        "https://ixo-api.ibs.team",
        "https://proxies.sifchain.finance/api/impacthub-3/rest",
        "https://impacthub.ixo.world/rest",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "IXO",
      symbol: "IXO",
      denom: "uixo",
      decimals: 6,
    },
    name: "IXO",
    short_name: "IXO",
    image: "/logos/chains/ixo.svg",
    color: "#012d42",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/ixo",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "ixo",
    prefix_chain_ids: ["ixo-"],
    id: "ixo",
    chain_type: "cosmos",
  },
  {
    chain_id: "migaloo-1",
    chain_name: "migaloo",
    endpoints: {
      lcd: [
        "https://migaloo-api.polkachu.com",
        "https://migaloo-api.lavenderfive.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "White Whale",
      symbol: "WHALE",
      denom: "uwhale",
      decimals: 6,
    },
    name: "White Whale",
    short_name: "WHALE",
    image: "/logos/chains/migaloo.svg",
    color: "#3dcd64",
    explorer: {
      name: "Rebus",
      url: "https://migaloo.explorers.guru",
      icon: "/logos/explorers/migaloo.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/transaction/{tx}",
    },
    prefix_address: "migaloo",
    prefix_chain_ids: ["migaloo-"],
    id: "migaloo",
    chain_type: "cosmos",
  },
  {
    chain_id: "teritori-1",
    chain_name: "teritori",
    endpoints: {
      lcd: [
        "https://teritori-api.lavenderfive.com",
        "https://teritori-api.polkachu.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Teritori",
      symbol: "TORI",
      denom: "utori",
      decimals: 6,
    },
    name: "Teritori",
    short_name: "TORI",
    image: "/logos/chains/teritori.svg",
    color: "#428fff",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/teritori",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "tori",
    prefix_chain_ids: ["teritori-"],
    id: "teritori",
    chain_type: "cosmos",
  },
  {
    chain_id: "haqq_11235-1",
    chain_name: "haqq",
    endpoints: {
      lcd: [
        "https://api-1.haqq.nodes.guru",
        "https://rest.cosmos.haqq.network",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Islamic",
      symbol: "ISLM",
      denom: "uislm",
      decimals: 6,
    },
    name: "Haqq",
    short_name: "HAQQ",
    image: "/logos/chains/haqq.svg",
    color: "#ec5728",
    explorer: {
      name: "Haqq",
      url: "https://ping.pub/haqq",
      icon: "/logos/explorers/haqq.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/tx/{tx}",
    },
    prefix_address: "haqq",
    prefix_chain_ids: ["haqq_"],
    id: "haqq",
    chain_type: "cosmos",
  },
  {
    chain_id: "celestia",
    chain_name: "celestia",
    endpoints: {
      lcd: [
        "https://celestia-api.polkachu.com",
        "https://public-celestia-lcd.numia.xyz",
        "https://celestia-rest.mesa.newmetric.xyz",
        "https://api.lunaroasis.net",
        "https://api.celestia.nodestake.top",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Celestia",
      symbol: "TIA",
      denom: "utia",
      decimals: 6,
    },
    name: "Celestia",
    short_name: "TIA",
    image: "/logos/chains/celestia.svg",
    color: "#7b2af9",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/celestia",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "celestia",
    prefix_chain_ids: ["celestia"],
    id: "celestia",
    chain_type: "cosmos",
  },
  {
    chain_id: "agamotto",
    chain_name: "ojo",
    endpoints: {
      lcd: ["https://api.agamotto-val-stage-0.ojo.network"],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Ojo",
      symbol: "OJO",
      denom: "uojo",
      decimals: 6,
    },
    name: "Ojo",
    short_name: "OJO",
    image: "/logos/chains/ojo.svg",
    color: "#fb4746",
    explorer: {
      name: "Ojo",
      url: "https://agamotto.ojo.network/agamotto",
      icon: "/logos/explorers/ojo.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/tx/{tx}",
    },
    prefix_address: "ojo",
    prefix_chain_ids: ["agamotto"],
    id: "ojo",
    chain_type: "cosmos",
  },
  {
    chain_id: "chihuahua-1",
    chain_name: "chihuahua",
    endpoints: {
      lcd: [
        "https://chihuahua-api.polkachu.com",
        "https://api.chihuahua.wtf",
        "https://rest-chihuahua.ecostake.com",
        "https://api-chihuahua-ia.cosmosia.notional.ventures",
        "https://chihuahua-api.lavenderfive.com",
        "https://chihuahua-api.kleomedes.network",
        "https://api-chihuahua.pupmos.network",
        "https://chihuahua-mainnet-lcd.autostake.com",
        "https://chihuahua-rest.publicnode.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Chihuahua",
      symbol: "HUAHUA",
      denom: "uhuahua",
      decimals: 6,
    },
    name: "Chihuahua",
    short_name: "HUAHUA",
    image: "/logos/chains/chihuahua.svg",
    color: "#fed52e",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/chihuahua",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "chihuahua",
    prefix_chain_ids: ["chihuahua-"],
    id: "chihuahua",
    chain_type: "cosmos",
  },
  {
    chain_id: "ssc-1",
    chain_name: "saga",
    endpoints: {
      lcd: [
        "https://ssc-lcd.sagarpc.io",
        "https://saga-rest.publicnode.com",
        "https://api.saga.nodestake.org",
        "https://saga.api.kjnodes.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Saga",
      symbol: "SAGA",
      denom: "usaga",
      decimals: 6,
    },
    name: "Saga",
    short_name: "SAGA",
    image: "/logos/chains/saga.svg",
    color: "#000000",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/saga",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "saga",
    prefix_chain_ids: ["ssc-"],
    id: "saga",
    chain_type: "cosmos",
  },
  {
    chain_id: "dymension_1100-1",
    chain_name: "dymension",
    endpoints: {
      lcd: [
        "https://dymension-api.polkachu.com",
        "https://dymension-api.lavenderfive.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Dymension",
      symbol: "DYM",
      denom: "udym",
      decimals: 6,
    },
    name: "Dymension",
    short_name: "DYM",
    image: "/logos/chains/dymension.svg",
    color: "#000000",
    explorer: {
      name: "Dymension",
      url: "https://dymension.explorers.guru",
      icon: "/logos/explorers/dymension.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/transaction/{tx}",
    },
    prefix_address: "dym",
    prefix_chain_ids: ["dymension_"],
    id: "dymension",
    chain_type: "cosmos",
  },
  {
    chain_id: "fxcore",
    chain_name: "fxcore",
    endpoints: {
      lcd: ["https://fx-rest.functionx.io:1317"],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Function X",
      symbol: "FX",
      denom: "ufx",
      decimals: 6,
    },
    name: "Function X",
    short_name: "FX",
    image: "/logos/chains/fxcore.svg",
    color: "#020a12",
    explorer: {
      name: "FxCore",
      url: "https://ping.pub/fxcore",
      icon: "/logos/explorers/fxcore.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/tx/{tx}",
    },
    prefix_address: "fx",
    prefix_chain_ids: ["fxcore"],
    id: "fxcore",
    chain_type: "cosmos",
  },
  {
    chain_id: "perun-1",
    chain_name: "c4e",
    endpoints: {
      lcd: [
        "https://lcd.c4e.io",
        "https://chain4energy-mainnet-lcd.autostake.com",
        "https://c4e.api.m.stavr.tech",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Chain4Energy",
      symbol: "C4E",
      denom: "uc4e",
      decimals: 6,
    },
    name: "Chain4Energy",
    short_name: "C4E",
    image: "/logos/chains/c4e.svg",
    color: "#77b229",
    explorer: {
      name: "Chain4Energy",
      url: "https://explorer.c4e.io",
      icon: "/logos/explorers/c4e.png",
      block_path: "/blocks/{block}",
      address_path: "/accounts/{address}",
      contract_path: "/accounts/{address}",
      transaction_path: "/transactions/{tx}",
    },
    prefix_address: "c4e",
    prefix_chain_ids: ["perun-"],
    id: "c4e",
    chain_type: "cosmos",
  },
  {
    chain_id: "bitsong-2b",
    chain_name: "bitsong",
    endpoints: {
      lcd: [
        "https://bitsong-api.polkachu.com",
        "https://bitsong-api.lavenderfive.com",
        "https://api-bitsong-ia.cosmosia.notional.ventures",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Bitsong",
      symbol: "BTSG",
      denom: "ubtsg",
      decimals: 6,
    },
    name: "Bitsong",
    short_name: "BTSG",
    image: "/logos/chains/bitsong.svg",
    color: "#f2533c",
    explorer: {
      name: "Mintscan",
      url: "https://www.mintscan.io/bitsong",
      icon: "/logos/explorers/mintscan.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/txs/{tx}",
      asset_path: "/assets/ibc/{ibc_denom}",
    },
    prefix_address: "bitsong",
    prefix_chain_ids: ["bitsong-"],
    id: "bitsong",
    chain_type: "cosmos",
  },
  {
    chain_id: "pirin-1",
    chain_name: "nolus",
    endpoints: {
      lcd: [
        "https://pirin-cl.nolus.network:1317",
        "https://nolus-api.lavenderfive.com",
        "https://nolus-mainnet-lcd.autostake.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Nolus",
      symbol: "NLS",
      denom: "unls",
      decimals: 6,
    },
    name: "Nolus",
    short_name: "NLS",
    image: "/logos/chains/nolus.svg",
    color: "#fd472c",
    explorer: {
      name: "Nolus",
      url: "https://ping.pub/nolus",
      icon: "/logos/explorers/nolus.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/tx/{tx}",
    },
    prefix_address: "nolus",
    prefix_chain_ids: ["pirin-"],
    id: "nolus",
    chain_type: "cosmos",
  },
  {
    chain_id: "lava-mainnet-1",
    chain_name: "lava",
    endpoints: {
      lcd: [
        "https://lava-api.w3coins.io",
        "https://lava-api.ibs.team",
        "https://api.lava-mainnet-1.lava.aviaone.com",
        "https://lava-rest.publicnode.com",
        "https://lava.api.m.stavr.tech",
        "https://lava.api-archive.m.stavr.tech",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Lava",
      symbol: "LAVA",
      denom: "ulava",
      decimals: 6,
    },
    name: "Lava",
    short_name: "LAVA",
    image: "/logos/chains/lava.svg",
    color: "#ff3900",
    explorer: {
      name: "Lava",
      url: "https://lava.explorers.guru",
      icon: "/logos/explorers/lava.png",
      block_path: "/block/{block}",
      address_path: "/account/{address}",
      contract_path: "/account/{address}",
      transaction_path: "/transaction/{tx}",
    },
    prefix_address: "lava@",
    prefix_chain_ids: ["lava-mainnet-"],
    id: "lava",
    chain_type: "cosmos",
  },
  {
    chain_id: "phoenix-1",
    chain_name: "terra-2",
    endpoints: {
      lcd: [
        "https://phoenix-lcd.terra.dev",
        "https://lcd-terra.imperator.co",
        "https://terra-api.polkachu.com",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Terra",
      symbol: "LUNA",
      denom: "uluna",
      decimals: 6,
    },
    name: "Terra",
    short_name: "TERRA",
    image: "/logos/chains/terra-2.svg",
    color: "#ffd83d",
    explorer: {
      name: "Terra",
      url: "https://finder.terra.money/mainnet",
      icon: "/logos/explorers/terra.png",
      block_path: "/blocks/{block}",
      address_path: "/address/{address}",
      contract_path: "/address/{address}",
      transaction_path: "/tx/{tx}",
    },
    prefix_address: "terra",
    prefix_chain_ids: ["phoenix-"],
    id: "terra-2",
    chain_type: "cosmos",
  },
  {
    chain_id: "columbus-5",
    chain_name: "terra",
    aliases: ["terra classic"],
    endpoints: {
      lcd: [
        "https://api-terra-ia.cosmosia.notional.ventures",
        "https://columbus-lcd.terra.dev",
        "https://terra-classic-lcd.publicnode.com",
        "https://terraclassic-mainnet-lcd.autostake.com",
        "https://lcd.terra.dev",
      ],
      timeout: {
        lcd: 3000,
      },
    },
    native_token: {
      name: "Terra",
      symbol: "LUNA",
      denom: "uluna",
      decimals: 6,
    },
    name: "Terra Classic",
    short_name: "TERRAC",
    image: "/logos/chains/terra.png",
    color: "#ffd83d",
    explorer: {
      name: "Terra",
      url: "https://finder.terra.money/classic",
      icon: "/logos/explorers/terra.png",
      block_path: "/blocks/{block}",
      address_path: "/address/{address}",
      contract_path: "/address/{address}",
      transaction_path: "/tx/{tx}",
    },
    prefix_address: "terra",
    prefix_chain_ids: ["columbus-"],
    id: "terra",
    chain_type: "cosmos",
  },
];
